table DIM_Vertical
	lineageTag: 79895589-607a-4461-94e9-8634fac71463

	column Vertical
		dataType: string
		lineageTag: 94bfd5d0-9f85-40a1-a7eb-6e3e30b44027
		summarizeBy: none
		sourceColumn: Vertical

		annotation SummarizationSetBy = Automatic

	column VerticalID
		dataType: int64
		formatString: 0
		lineageTag: fefa7fd5-bf9d-4b86-bf58-7dcf900fd278
		summarizeBy: none
		sourceColumn: VerticalID

		annotation SummarizationSetBy = Automatic

	partition DIM_Vertical = m
		mode: import
		source =
				let
				    FuentePA = Table.SelectColumns(stgRealPA, {"Vertical"}),
				    Real = Table.SelectColumns(stgBaseRealCruda, {"Vertical"}),
				    Union = Table.Combine({FuentePA, Real}),
				    Distinct = Table.Distinct(Union),
				    SinNulos = Table.SelectRows(Distinct, each [Vertical] <> null and [Vertical] <> ""),
				    Ordenado = Table.Sort(SinNulos, {{"Vertical", Order.Ascending}}),
				    ConID = Table.AddIndexColumn(Ordenado, "VerticalID", 1, 1, Int64.Type),
				    Tipos = Table.TransformColumnTypes(ConID, {{"VerticalID", Int64.Type}, {"Vertical", type text}})
				in
				    Tipos

	annotation PBI_ResultType = Table

