table DIM_Ceco
	lineageTag: 99a8fbfb-9517-4fd2-8d0b-1f30f32633f5

	column Ceco
		dataType: string
		lineageTag: 5f536f8d-a938-4dfe-8a73-f15da938d945
		summarizeBy: none
		sourceColumn: Ceco

		annotation SummarizationSetBy = Automatic

	column CecoID
		dataType: int64
		formatString: 0
		lineageTag: 5821a78d-c9ec-4efe-833b-b0c63e23a178
		summarizeBy: none
		sourceColumn: CecoID

		annotation SummarizationSetBy = Automatic

	partition DIM_Ceco = m
		mode: import
		source =
				let
				    FuentePA = Table.SelectColumns(stgRealPA, {"Ceco"}),
				    Real = Table.SelectColumns(stgBaseRealCruda, {"Ceco"}),
				    Union = Table.Combine({FuentePA, Real}),
				    Distinct = Table.Distinct(Union),
				    SinNulos = Table.SelectRows(Distinct, each [Ceco] <> null and [Ceco] <> ""),
				    Ordenado = Table.Sort(SinNulos, {{"Ceco", Order.Ascending}}),
				    ConID = Table.AddIndexColumn(Ordenado, "CecoID", 1, 1, Int64.Type),
				    Tipos = Table.TransformColumnTypes(ConID, {{"CecoID", Int64.Type}, {"Ceco", type text}})
				in
				    Tipos

	annotation PBI_ResultType = Table

